# OrangeFox Build Configuration for NX669J
PRODUCT_MAKEFILES := \
    $(LOCAL_DIR)/fox_NX669J.mk

# Device information
PRODUCT_DEVICE := NX669J
PRODUCT_NAME := orangefox_NX669J
PRODUCT_BRAND := Nubia
PRODUCT_MODEL := Red Magic 6S
PRODUCT_MANUFACTURER := Nubia

# OrangeFox-specific flags
FOX_VERSION := "R11.1"
FOX_BUILD_DEVICE := "NX669J"
FOX_USE_TWRP_RECOVERY_IMAGE_BUILDER := true
FOX_RECOVERY_INSTALL_PARTITION := "/dev/block/bootdevice/by-name/boot"
FOX_AB_DEVICE := true
FOX_USE_BASH_SHELL := true
FOX_ASH_IS_BASH := true
FOX_USE_NANO_EDITOR := true
FOX_USE_TAR_BINARY := true
FOX_USE_SED_BINARY := true
FOX_USE_XZ_UTILS := true
FOX_REPLACE_BUSYBOX_PS := true
FOX_USE_GREP_BINARY := true
FOX_USE_UNZIP_BINARY := true
FOX_USE_ZIP_BINARY := true
FOX_USE_LZMA_COMPRESSION := true
OF_USE_LZMA_COMPRESSION := true
FOX_ADVANCED_SECURITY := true
FOX_USE_SPECIFIC_MAGISK_ZIP := device/nubia/NX669J/Magisk.zip

# Dynamic Partitions & Super Unmap
OF_DYNAMIC_PARTITIONS := true
OF_DISABLE_DM_VERITY := true
OF_DISABLE_FORCED_ENCRYPTION := true
OF_PATCH_AVB20 := true
OF_NO_TREBLE_COMPATIBILITY_CHECK := true
OF_USE_MAGISKBOOT := true
OF_USE_MAGISKBOOT_FOR_ALL_PATCHES := true
OF_DONT_PATCH_ENCRYPTED_DEVICE := true
OF_SUPPORT_OZIP_DECRYPTION := true

# Screen Configuration
OF_SCREEN_H := 2400
OF_STATUS_H := 80
OF_STATUS_INDENT_LEFT := 48
OF_STATUS_INDENT_RIGHT := 48
OF_HIDE_NOTCH := 1
OF_CLOCK_POS := 1
OF_USE_GREEN_LED := 0
OF_FLASHLIGHT_ENABLE := 0

# OTA & ROM flashing support
OF_SUPPORT_ALL_BLOCK_OTA_UPDATES := true
OF_FIX_OTA_UPDATE_MANUAL_FLASH_ERROR := true
OF_RUN_POST_FORMAT_PROCESS := true

# Additional Configurations
FOX_DELETE_AROMAFM := true
FOX_ENABLE_APP_MANAGER := true
TARGET_OTA_ASSERT_DEVICE := NX669J

# Include common TWRP/OrangeFox configurations
$(call inherit-product, vendor/twrp/config/common.mk)
